public class Human {
//Properties Or variables	
    Public String dob;
    Public String height;
    Public String weight;
    Public String color;
    Public String name;
  //Method Creation   
    Public Void eat(){
		system.debug('This method is to handle eating'+this.name);        
    }
    
    Public Void walk(){
		system.debug('This method is to handle Walk' +this.name);        
    }
    
    Public Void sleep(){
		system.debug('This method is to handle Sleep'+this.name);        
    }
    
    Public Void read(){
		system.debug('This method is to handle reading'+this.name);        
    }
    
}