public class maruthicar implements carinterface {
	
    public void marthicar(){
        system.debug('This is as same as the parent class');
    }
    
    public void engine(){
        system.debug('this implementation is from CI_ engine_class');
    }
    
    public void tyres(){
        system.debug('this implementation is from CI_tyres_class');
    }
    
    public void sensors(){
        system.debug('this implementation is from CI_sensors_class');
    }
    
    public void accessories(){
        system.debug('this implementation is from CI_accessories_class');
    }
    
}